<?php

namespace App\Filament\Market\Resources\Inventories\Pages;

use App\Filament\Market\Resources\Inventories\InventoryResource;
use App\Models\Item;
use App\Models\Place_stock;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Arr;

class CreateInventory extends CreateRecord
{
    protected ?string $heading='';
    protected static string $resource = InventoryResource::class;
    protected function getFormActions(): array
    {
        return [
            $this->getCreateAnotherFormAction()
                ->label('تخزين'),
            $this->getCancelFormAction(),
        ];
    }
    protected function preserveFormDataWhenCreatingAnother(array $data): array
    {
        return Arr::only($data, ['place_id', ]);
    }
    protected function mutateFormDataBeforeCreate(array $data): array
    {

        $place=Place_stock::find($data['place_stock_id']);
        $item=Item::find($data['item_id']);
        $difference=$data['actual_balance']-$item->stock1;
        $data['difference']=$difference;
        $data['its_value']=$difference*$item->price_buy;
        $place->stock1=$data['actual_balance'];
        $place->inventory_balance+=$difference;
        $place->save();

        $item->stock1+=$difference;
        $item->save();
        return $data; // TODO: Change the autogenerated stub
    }

}
