<?php

namespace App\Filament\market\Resources\Items\Pages;

use App\Filament\market\Resources\Items\ItemResource;
use App\Models\Barcode;
use App\Models\Buy_tran;
use App\Models\Buy_tran_work;
use App\Models\Item;
use App\Models\Sell_tran;
use App\Models\Sell_tran_work;
use App\Models\Setting;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Auth;

class EditItem extends EditRecord
{
    protected static string $resource = ItemResource::class;
  protected ?string $heading="";

    protected function mutateFormDataBeforeSave(array $data): array
    {
        if (Setting::find(Auth::user()->company)->barcode)
        {
            $item=Item::find($data['id']);
            if ($item->barcode!=$data['barcode']) {

                Barcode::find($item->barcode)->update(['id'=>$data['barcode']]);
            }
        }

        return $data; // TODO: Change the autogenerated stub
    }
}
