<?php

namespace App\Filament\Resources\ItemResource\Pages;

use App\Filament\Resources\ItemResource;
use App\Models\Barcode;
use App\Models\Item;
use App\Models\Price_buy;
use App\Models\Setting;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Facades\Auth;

class CreateItem extends CreateRecord
{
    protected static string $resource = ItemResource::class;
    protected static bool $canCreateAnother = false;
    protected ?string $heading="";

    protected function mutateFormDataBeforeCreate(array $data): array
    {


        if (!Setting::find(Auth::user()->company)->barcode)
        {
            $data['barcode']=Barcode::max('id')+1;

        }

        $data['user_id'] = auth()->id();

        return $data; // TODO: Change the autogenerated stub
    }
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('create');
    }
}
