<?php

namespace App\Filament\Resources\ItemResource\Pages;

use App\Filament\Resources\ItemResource;
use App\Models\Barcode;
use App\Models\Item;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateItem extends CreateRecord
{
    protected static string $resource = ItemResource::class;
    protected static bool $canCreateAnother = false;
    protected ?string $heading="";

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id'] = auth()->id();

        return $data; // TODO: Change the autogenerated stub
    }
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('create');
    }
}
