<?php

namespace App\Filament\Resources\ItemResource\Pages;

use App\Filament\Resources\ItemResource;
use App\Models\Barcode;
use App\Models\Item;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateItem extends CreateRecord
{
    protected static string $resource = ItemResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id'] = auth()->id();

        return $data; // TODO: Change the autogenerated stub
    }
    protected function afterCreate(): void
    {
        $item=Item::latest()->first();
        $bar = new Barcode;
        $bar->barcode=$item->barcode;
        $bar->item_id=$item->id;
        $bar->save();

    }
}
