<?php

namespace App\Filament\market\Resources\ItemResource\Pages;

use App\Filament\market\Resources\ItemResource;
use App\Models\Barcode;
use App\Models\Buy_tran;
use App\Models\Buy_tran_work;
use App\Models\Item;
use App\Models\Sell_tran;
use App\Models\Sell_tran_work;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;

class EditItem extends EditRecord
{
    protected static string $resource = ItemResource::class;
  protected ?string $heading="";

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $item=Item::find($data['id']);
        if ($item->barcode!=$data['barcode']) {

            Barcode::find($item->barcode)->update(['id'=>$data['barcode']]);
        }
        return $data; // TODO: Change the autogenerated stub
    }
}
