<?php

namespace App\Filament\market\Resources\SellWorkResource\Pages;

use App\Filament\market\Resources\SellWorkResource;
use App\Models\Sell_work;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Support\Facades\Auth;

class ListSellWorks extends ListRecords
{
    protected ?string $heading='ادخال فواتير مبيعات';
    protected static string $resource = SellWorkResource::class;

    public function mount(): void
    {

        parent::mount(); // TODO: Change the autogenerated stub

        $sell=Sell_work::find(Auth::id());
        if ($sell && $sell->place_id != Auth::user()->place_id) $sell->delete();
        if (!Sell_work::find(Auth::id()))
        {
            if (Auth::user()->hasRole('admin'))
                Sell_work::create([
                    'id'=>Auth::id(),'user_id'=>Auth::id(),'customer_id'=>1,
                ]);
            else
                Sell_work::create([
                    'id'=>Auth::id(),'user_id'=>Auth::id(),'customer_id'=>1,'place_id'=>Auth::user()->place_id,
                ]);
        }


    }

}
