<?php

namespace App\Filament\market\Resources\RecsuppResource\Pages;

use App\Filament\market\Resources\RecsuppResource;
use App\Models\Buy;
use App\Models\Kazena;
use App\Models\Recsupp;
use Filament\Actions\DeleteAction;
use Filament\Forms\Get;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Auth;

class EditRecsupp extends EditRecord
{
    protected static string $resource = RecsuppResource::class;
  protected ?string $heading='';

 public $buy_to_save;
 public $rec_who;
    protected function mutateFormDataBeforeFill(array $data): array
    {
        if ($data['price_type_id']==1) {
            $res=Kazena::where('user_id',Auth::id())->first();
            if ($res) $data['kazena_id']=$res->id;
        }
        if (Auth::user()->place_id!=null) $data['place_id']= Auth::user()->place_id;


        return $data;
    }

    protected function mutateFormDataBeforeSave(array $data): array
  {
      $this->rec_who=$data['rec_who'];
      if ($this->rec_who == 3 || $this->rec_who == 4 || $this->rec_who == 5 || $this->rec_who == 6)
        $this->buy_to_save=$data['buy_id'];


    return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
  }
    protected function afterSave(): void
    {
        if ($this->rec_who == 3 || $this->rec_who == 4 || $this->rec_who == 5 || $this->rec_who == 6)
        {

            $imp=Recsupp::where('buy_id',$this->buy_to_save)->whereIn('rec_who',[3,6])
                ->sum('val');
            $exp=Recsupp::where('buy_id',$this->buy_to_save)->whereIn('rec_who',[4,5])
                ->sum('val');
            $buy=Buy::find($this->buy_to_save);
            $buy->pay=$exp-$imp;
            $buy->baky=$buy->tot-$buy->pay;
            $buy->save();
        }
    }

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make()->visible(Auth::user()->can('الغاء ايصالات موردين')),
        ];
    }
}
