<?php

namespace App\Filament\Resources\SalaryResource\Pages;

use App\Filament\Resources\SalaryResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateSalary extends CreateRecord
{
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('create');
    }
    public static ?string $title = 'ادخال مرتب';
    protected static string $resource = SalaryResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['status'] = 1;
        $data['raseed'] = 0;
        return $data; // TODO: Change the autogenerated stub
    }
}
