<?php

namespace App\Filament\Resources\RecsuppResource\Pages;

use App\Filament\Resources\RecsuppResource;
use App\Models\Buy;
use App\Models\Receipt;
use App\Models\Recsupp;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateRecsupp extends CreateRecord
{
    protected static string $resource = RecsuppResource::class;
  protected ?string $heading="";
    protected static bool $canCreateAnother = false;
  protected function getRedirectUrl(): string
  {
    return $this->getResource()::getUrl('create');
  }

  protected function mutateFormDataBeforeCreate(array $data): array
  {
      switch ($data['rec_who']) {
          case 1: $data['imp_exp']=0;break;
          case 2: $data['imp_exp']=1;break;
          case 3: $data['imp_exp']=0;break;
          case 4: $data['imp_exp']=1;break;
      }
    if ($data['rec_who'] == 3 || $data['rec_who'] == 4)
    {   $val=$data['val'];
        $imp=Recsupp::where('buy_id',$data['buy_id'])->whereIn('rec_who',[3,6])->sum('val');
        $exp=Recsupp::where('buy_id',$data['buy_id'])->whereIn('rec_who',[4,5])->sum('val');

        if ($data['rec_who'] == 3) $imp+=$val;
        if ($data['rec_who'] == 4) $exp+=$val;
      $buy=Buy::find($data['buy_id']);
      $buy->pay=$exp-$imp;
      $buy->baky=$buy->tot-$buy->pay;
      $buy->save();
    }
    return $data; // TODO: Change the autogenerated stub
  }

}
