<?php

namespace App\Filament\Resources\RecsuppResource\Pages;

use App\Filament\Resources\RecsuppResource;
use App\Models\Buy;
use App\Models\Recsupp;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateRecsupp extends CreateRecord
{
    protected static string $resource = RecsuppResource::class;
  protected ?string $heading="";
  protected function getRedirectUrl(): string
  {
    return $this->getResource()::getUrl('create');
  }

  protected function mutateFormDataBeforeCreate(array $data): array
  {
    if ($data['rec_who'] == 3 || $data['rec_who'] == 4)
    {   $val=$data['val'];
      $sum=Recsupp::where('buy_id',$data['buy_id'])->sum('val');
      if ($data['rec_who'] == 3) $val+=$sum;
      if ($data['rec_who'] == 4) $val=$sum-$val;
      $buy=Buy::find($data['buy_id']);
      $buy->pay=$val;
      $buy->baky=$buy->tot-$buy->pay;
      $buy->save();
    }
    return $data; // TODO: Change the autogenerated stub
  }

}
