<?php

namespace App\Filament\Resources\RecsuppResource\Pages;

use App\Filament\Resources\RecsuppResource;
use App\Models\Buy;
use App\Models\Receipt;
use App\Models\Recsupp;
use Filament\Actions;
use Filament\Forms\Get;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Auth;

class EditRecsupp extends EditRecord
{
    protected static string $resource = RecsuppResource::class;
  protected ?string $heading='';

 public $buy_to_save;
 public $rec_who;

    protected function mutateFormDataBeforeSave(array $data): array
  {
      $this->buy_to_save=$data['buy_id'];
      $this->rec_who=$data['rec_who'];

    return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
  }
    protected function afterSave(): void
    {
        if ($this->rec_who == 3 || $this->rec_who == 4 || $this->rec_who == 5 || $this->rec_who == 6)
        {

            $imp=Recsupp::where('buy_id',$this->buy_to_save)->whereIn('rec_who',[3,6])
                ->sum('val');
            $exp=Recsupp::where('buy_id',$this->buy_to_save)->whereIn('rec_who',[4,5])
                ->sum('val');
            $buy=Buy::find($this->buy_to_save);
            $buy->pay=$exp-$imp;
            $buy->baky=$buy->tot-$buy->pay;
            $buy->save();
        }
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make()->visible(Auth::user()->can('الغاء ايصالات موردين')),
        ];
    }
}
