<?php

namespace App\Filament\market\Resources\BuysWorkResource\Pages;

use App\Filament\market\Resources\BuysWorkResource;
use App\Models\Buys_work;
use Filament\Actions\CreateAction;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Support\Facades\Auth;

class ListBuysWorks extends ListRecords
{
    protected static string $resource = BuysWorkResource::class;

    protected ?string $heading='';
    protected function getHeaderActions(): array
    {
        return [
            CreateAction::make()
          ->label('ادخال أصتاف للفاتورة'),


        ];
    }
    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub

        if (!Buys_work::find(Auth::id()))
            Buys_work::create([
                'id'=>Auth::id(),'user_id'=>Auth::id(),
            ]);


    }
}
