<?php

namespace App\Filament\Resources\MoneyResource\Pages;

use App\Filament\Resources\MoneyResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateMoney extends CreateRecord
{
    protected static string $resource = MoneyResource::class;
    protected ?string $heading='';
  protected static bool $canCreateAnother = false;

  protected function getRedirectUrl(): string
  {
    return $this->getResource()::getUrl('create');
  }
    protected function mutateFormDataBeforeCreate(array $data): array
    {


        switch ($data['rec_who']) {
            case 1: $data['acc_id']=null;$data['acc2_id']=null;break;
            case 2: $data['kazena2_id']=null;$data['acc_id']=null;break;
            case 3: $data['kazena_id']=null;$data['acc2_id']=null;break;
            case 4: $data['kazena2_id']=null;$data['kazena_id']=null;break;
        }

        return $data; // TODO: Change the autogenerated stub
    }

}
