<?php

namespace App\Filament\Resources\ReceiptResource\Pages;

use App\Filament\Resources\ReceiptResource;
use App\Models\Kazena;
use App\Models\Receipt;
use App\Models\Sell;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Facades\Auth;

class CreateReceipt extends CreateRecord
{
    protected static string $resource = ReceiptResource::class;
    protected ?string $heading="";
    protected static bool $canCreateAnother = false;
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('create');
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        switch ($data['rec_who']) {
            case 1: $data['imp_exp']=0;break;
            case 2: $data['imp_exp']=1;break;
            case 3: $data['imp_exp']=0;break;
            case 4: $data['imp_exp']=1;break;
        }
        if ($data['price_type_id']==1) {
            $res=Kazena::where('user_id',Auth::id())->first();
            if ($res) $data['kazena_id']=$res->id;
        }
        if (Auth::user()->place_id!=null) $data['place_id']= Auth::user()->place_id;

        if ($data['rec_who'] == 3 || $data['rec_who'] == 4)
        {   $val=$data['val'];
            $imp=Receipt::where('sell_id',$data['sell_id'])->whereIn('rec_who',[3,6])->sum('val');
            $exp=Receipt::where('sell_id',$data['sell_id'])->whereIn('rec_who',[4,5])->sum('val');

            if ($data['rec_who'] == 3) $imp+=$val;
            if ($data['rec_who'] == 4) $exp+=$val;
            $sell=Sell::find($data['sell_id']);
            $sell->pay=$imp-$exp;
            $sell->baky=$sell->total-$sell->pay;
            $sell->save();
        }
        return $data; // TODO: Change the autogenerated stub
    }
}


