<?php

namespace App\Filament\Resources\ReceiptResource\Pages;

use App\Filament\Resources\ReceiptResource;
use App\Models\Receipt;
use App\Models\Sell;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateReceipt extends CreateRecord
{
    protected static string $resource = ReceiptResource::class;
    protected ?string $heading="";
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('create');
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        if ($data['rec_who'] == 3 || $data['rec_who'] == 4)
        {   $val=$data['val'];
            $sum=Receipt::where('sell_id',$data['sell_id'])->sum('val');
            if ($data['rec_who'] == 3) $val+=$sum;
            if ($data['rec_who'] == 4) $val=$sum-$val;
            $sell=Sell::find($data['sell_id']);
            $sell->pay=$val;
            $sell->baky=$sell->tot-$sell->pay;
            $sell->save();
        }
        return $data; // TODO: Change the autogenerated stub
    }
}


