<?php

namespace App\Filament\Resources\ReceiptResource\Pages;

use App\Filament\Resources\ReceiptResource;
use App\Models\Receipt;
use App\Models\Sell;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditReceipt extends EditRecord
{
    protected static string $resource = ReceiptResource::class;
    protected ?string $heading='';

    protected function mutateFormDataBeforeSave(array $data): array
    {
        if ($data['rec_who'] == 3 || $data['rec_who'] == 4)
        {   $val=$data['val'];
            $val+=Receipt::where('sell_id',$data['sell_id'])->sum('val');

            $sell=Sell::find($data['sell_id']);
            $sell->pay=$val;
            $sell->baky=$sell->tot-$sell->pay;
            $sell->save();

        }
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make()

        ];
    }
}
