<?php

namespace App\Filament\Resources\ReceiptResource\Pages;

use App\Filament\Resources\ReceiptResource;
use App\Models\Receipt;
use App\Models\Sell;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditReceipt extends EditRecord
{
    protected static string $resource = ReceiptResource::class;
    protected ?string $heading='';

    public $sell_to_save;
    public $rec_who;
    protected function afterSave(): void
    {
        if ($this->rec_who == 3 || $this->rec_who == 4 || $this->rec_who == 5 || $this->rec_who == 6)
        {
            $imp=Receipt::where('sell_id',$this->sell_to_save)->wherein('rec_who',[3,6])
                ->sum('val');
            $exp=Receipt::where('sell_id',$this->sell_to_save)->wherein('rec_who',[4,5])
                ->sum('val');

            $sell=Sell::find($this->sell_to_save);
            $sell->pay=$imp-$exp;
            $sell->baky=$sell->total-$sell->pay;
            $sell->save();
        }
    }
    protected function mutateFormDataBeforeSave(array $data): array
    {
        $this->sell_to_save=$data['sell_id'];
        $this->rec_who=$data['rec_who'];

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make()

        ];
    }
}
