<?php

namespace App\Filament\ins\Pages\Reports;

use App\Filament\ins\Resources\MainArcResource\Pages\ListMainArcs;
use App\Models\aksat\MainArc;
use App\Models\Main_arc;
use App\Models\stores\halls_names;
use App\Models\stores\stores_names;
use Filament\Actions\Action;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Infolists\Components\TextEntry;
use Filament\Pages\Page;
use Filament\Schemas\Components\Actions;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Illuminate\Support\HtmlString;
use Livewire\Attributes\On;

class ContAllThingArc extends Page implements HasForms
{
    use InteractsWithForms;
    protected static string | \BackedEnum | null $navigationIcon = 'heroicon-o-document-text';

    protected string $view = 'filament.ins.pages.cont-all-thing-arc';
    public static function shouldRegisterNavigation(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    protected ?string $heading='';
    public $contData;
    public $main_id;
    public Main_arc $Main;

    #[On('AllThingArc_id')]
    public function allThing($main_id)
    {
       $this->main_id=$main_id;
        $this->dispatch('Take_Main_Arc_Id',main_id: $main_id);
    }

   public function mount(){

       $this->main_id=request()->main_id;
       $this->contForm->fill([]);
       $this->Main=Main_arc::find($this->main_id);

   }


    protected function getForms(): array
    {
        return array_merge(parent::getForms(),[
            'contForm'=> $this->makeForm()

                ->components($this->getContFormSchema())
                ->statePath('contData'),
        ]);
    }
    protected function getContFormSchema(): array
    {
        return [
            Section::make()
                ->schema([
                    Actions::make([
                        Action::make('ret')
                            ->Label('عودة')
                            ->url(ListMainArcs::getUrl()),
                    ]),

                ]),
        ];
    }

    public function mainArcInfolist(Schema $schema): Schema
    {
        return $schema

            ->record($this->Main)
            ->components([
                TextEntry::make('Customer.name')
                    ->color('primary')
                    ->extraEntryWrapperAttributes(['style' => 'height: 16px;'])
                    ->hiddenLabel()
                    ->columnSpan(3),
                TextEntry::make('acc')
                    ->color('info')
                    ->prefix(new HtmlString('<span class="ttext-gray-600 dark:text-white "> رقم الحساب&nbsp;&nbsp;</span>'))
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->hiddenLabel()
                    ->columnSpan(3),
                TextEntry::make('Bank.BankName')
                    ->color('primary')
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->hiddenLabel()
                    ->columnSpan(3),

                TextEntry::make('Sell.Place.name')
                    ->prefix(new HtmlString('<span class="text-gray-600 dark:text-white "> نقطة البيع&nbsp;&nbsp;</span>'))
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->hiddenLabel()
                    ->color('info')


                    ->columnSpan(3),
                TextEntry::make('sul_begin')
                    ->color('info')
                    ->prefix(new HtmlString('<span class="text-gray-600 dark:text-white "> ت.العقد&nbsp;&nbsp;</span>'))
                    ->hiddenLabel()
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->columnSpan(2),
                TextEntry::make('Sell.tot')
                    ->color('info')
                    ->prefix(new HtmlString('<span class="text-gray-600 dark:text-white "> ج.الفاتورة&nbsp;&nbsp;</span>'))
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->hiddenLabel()
                    ->columnSpan(2),
                TextEntry::make('Sell_pay')
                    ->color('info')
                    ->state(function (){
                        return $this->Main->Sell->pay;
                    })
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->prefix(new HtmlString('<span class="text-gray-600 dark:text-white "> المدفوع&nbsp;&nbsp;</span>'))
                    ->hiddenLabel()
                    ->columnSpan(2),
                TextEntry::make('sul')
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->color('info')
                    ->prefix(new HtmlString('<span class="text-gray-600 dark:text-white "> ج.التقسيط&nbsp;&nbsp;</span>'))
                    ->hiddenLabel()
                    ->columnSpan(2),
                TextEntry::make('pay')
                    ->color('info')
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->prefix(new HtmlString('<span class="text-gray-600 dark:text-white "> المسدد&nbsp;&nbsp;</span>'))
                    ->hiddenLabel()
                    ->columnSpan(2),
                TextEntry::make('raseed')
                    ->color('danger')
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->prefix(new HtmlString('<span class="text-gray-600 dark:text-white"> المطلوب&nbsp;&nbsp;</span>'))
                    ->hiddenLabel()
                    ->columnSpan(2),
                TextEntry::make('kst_count')
                    ->color('info')
                    ->prefix(new HtmlString('<span class="text-gray-600 dark:text-white "> عدد الأقساط&nbsp;&nbsp;</span>'))
                    ->hiddenLabel()
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->columnSpan(2),
                TextEntry::make('kst')
                    ->color('info')
                    ->prefix(new HtmlString('<span class="text-gray-600 dark:text-white "> القسط&nbsp;&nbsp;</span>'))
                    ->hiddenLabel()
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->columnSpan(2),
                TextEntry::make('kst_baky')

                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])
                    ->color('info')
                    ->prefix(new HtmlString('<span class="text-gray-600 dark:text-white "> متبقية&nbsp;&nbsp;</span>'))
                    ->hiddenLabel()
                    ->columnSpan(2),
                TextEntry::make('notes')
                    ->color('success')
                    ->prefix(new HtmlString('<span class="text-gray-600 dark:text-white "> ملاحظات&nbsp;&nbsp;</span>'))
                    ->hiddenLabel()
                    ->visible(function (Main_arc $record){
                        return $record->notes!=null;
                    })
                    ->extraEntryWrapperAttributes(['style' => 'height: 12px;'])

                    ->columnSpan(6),

            ])->columns(6);
    }
}
